### ISSUE TITLE
vuex is a required dependency if you want to use "vuex" as storage

### ISSUE THREAD

**Issue by blackw212** [d0whc3r/vue-auth-plugin#109]
**Bug**
Getting this error that vuex is a required dependency, even if Vuex is installed explicitly. I use the JS version of Vue, and not the TS one.

**main.js file**

> import Vue from 'vue'
> import './plugins/vuetify'
> import './plugins/axios'
> import './plugins/vue-auth-plugin'
> import App from './App.vue'
> import router from './router'
> import store from './store'
>
> Vue.config.productionTip = false
>
> new Vue({
>   router,
>   store,
>   render: h => h(App)
> }).$mount('#app')

**store.js**
> import Vue from 'vue'
> import Vuex from 'vuex'
> import pathify from 'vuex-pathify'
> 
> Vue.use(Vuex)
> 
> const store = new Vuex.Store({
>     plugins: [ pathify.plugin ]
> })
> 
> Vue.store = store
> 
> export default store

**vue-auth-plugin.js**
> import Vue from 'vue'
> import VueAuth from '@d0whc3r/vue-auth-plugin'
> 
> const options = {
>     authMeta: 'auth',
>     rolesVar: 'roles',
>     tokenDefaultName: 'auth_token',
>     userDefaultName: 'auth_user',
>     tokenStore: ['vuex', 'cookie'],
>     headerTokenReplace: '{auth_token}',
>     tokenType: 'Bearer',
>     vuexStoreSpace: 'auth',
>   
>     authRedirect: '/login',
>   
>     loginData: {
>       url: '/auth/login',
>       method: 'POST',
>       redirect: '/user',
>       headerToken: 'Authorization',
>       fetchUser: false,
>     },
>     logoutData: {
>       url: '/auth/logout',
>       method: 'POST',
>       redirect: '/login',
>       makeRequest: false,
>     },
>   }
> 
> Vue.use(VueAuth, options)

What should i do ? been trying to find a solution for a quite a while, nothing helpful found.
Only one thing to mention, as in the documentation it is indeed state that you have to explicitly declare the store and the router - only exception being in my code, is that i cannot use `(Vue as any).store = store` as i am not using Typescript.

Thank you in advance !

**Comment by d0whc3r** [comment]
Try to change import order, and import vue-auth-plugin after router and store

**Comment by blackw212** [comment]
Indeed it worked, you are right! Thank you very much !
