### ISSUE TITLE
Getting User from authentication request body

### ISSUE THREAD

**Issue by hotsaucejake** [d0whc3r/vue-auth-plugin#154]
**Is your feature request related to a problem? Please describe.**
This is related to: https://github.com/d0whc3r/vue-auth-plugin/issues/118

**Describe the solution you'd like**
Similarly, my user object is passed in the response body from the authentication endpoint.  So I'm using `customToken: (response) => response.data['token'],` in the `loginData` options.  Is it possible to create a `customUser` that is also in the response like `customUser: (response) => response.data['user'],` ?

Or is there another way to set the user within loginData?

**Comment by hotsaucejake** [comment]
NVM, I created a route to get user info

**Comment by AdmiralNemo** [comment]
This functionality would be useful for me as well.  It would save an extra round-trip, since the server is sending the user metadata in the login response.

**Comment by d0whc3r** [comment]
ok I will add some mechanism to set user with login response

**Comment by d0whc3r** [comment]
You could use "fetchData" in "loginData" section
https://vue-auth-plugin.netlify.com/guide/#logindata
use version 1.6.0
