### ISSUE TITLE
2FA two-factor authentication support

### ISSUE THREAD

**Issue by TheGlenn88** [d0whc3r/vue-auth-plugin#164]
Are there any plans to integrate multi factor authentication, this will usually defer the retrieval of the token to a second login request of some sort, the first is a email + password auth, followed by a single use password check.

**Comment by d0whc3r** [comment]
There are some tools to integrate a 2FA in node, you could use it.
I don't think this feature needs to be in this plugin.
You could create a new window with a password prompt and send it to you server to verify the 2fa token
