### ISSUE TITLE
FetchData interval not start when refresh page

### ISSUE THREAD

**Issue by ArthurPai** [d0whc3r/vue-auth-plugin#172]
**Describe the bug**
If user is logged in, and then press F5 to refresh page.
The fetchData will not working.

**Solution**
May be on `AuthVueHttp.configureHttp`,
Checking token is exist, then call `AuthVueHttp.startIntervals`

Like this

```
  private configureHttp() {
    var token = this.storeManager.getToken()
    if (!!token) {
      this.startIntervals();
    }

    ....
  }
```

**Comment by d0whc3r** [comment]
Ok I will check as soon as I can
You could make a PR if you want

**Comment by ArthurPai** [comment]
I had make a PR, can you check it
