### ISSUE TITLE
Override default options in loginData or subojects.

### ISSUE THREAD

**Issue by Glandos** [d0whc3r/vue-auth-plugin#193]
**Describe the bug**
I'd like to override only one of the `loginData` options, e.g.:
```javascript
Vue.use(VueAuth, {
  loginData: {
    redirect: '/home',
  }
})
```

**Expected behavior**
All options described in docs should be set, like `method: 'POST'`

Instead, all `loginData` object is erased, and default options from axios are used.

Maybe I missed something?

**Comment by d0whc3r** [comment]
Now, you can import default_options configuration
https://github.com/d0whc3r/vue-auth-plugin/pull/199
https://vue-auth-plugin.netlify.com/installation.html#usage

**Comment by Glandos** [comment]
Thanks for that quick modifications.
I now use it, plus [Lodash.defaultsdeep](https://lodash.com/docs/4.17.15#defaultsDeep) to achieve this:
```js
import Vue from 'vue'
import VueAuth, { DEFAULT_OPTIONS } from '@d0whc3r/vue-auth-plugin'
import defaultsdeep from 'lodash/defaultsDeep'

Vue.use(VueAuth, defaultsdeep({
  tokenDefaultName: 'app_auth_token',
  userDefaultName: 'app_auth_user',
  tokenStore: ['vuex', 'localStorage'],
  loginData: {
    customToken: (response) => 'ABC'
  }
}, DEFAULT_OPTIONS))
```
And `loginData` is now correctly merged with default options.
