### ISSUE TITLE
[Documentation] False information in the Default Options section

### ISSUE THREAD

**Issue by dexax** [d0whc3r/vue-auth-plugin#220]
Branch: master
Documentation provides false information about the default options. 

The [Default options](https://d0whc3r.github.io/vue-auth-plugin/guide/#options) section in the Guide
suggests that the 
`customToken: (response) => response.data['token']` 
this is false in my opinion because this is not implemented anywhere.
The only place where is this implemented, is in the test :
`vue-auth-plugin/tests/integration/customToken.spec.ts `
but this mentioned test
test if is it possible to pass custom token getter, 
not the existence of the default one. 

**Expected behavior**
- Remove the misleading doc part
- OR Implement the missing part 
- OR explain in docs that by default the token is taken from the Header not from the response body

**Comment by d0whc3r** [comment]
Option is implemented here:
https://github.com/d0whc3r/vue-auth-plugin/blob/master/src/lib/auth-vue-http.ts#L195-L197

But your are right it is not a default option, documentation is wrong I will fix it asap

Thank you for your comment :)
