### ISSUE TITLE
Uncaught (in promise) Error: Avoided redundant navigation to current location: "/login".

### ISSUE THREAD

**Issue by janvorisek** [d0whc3r/vue-auth-plugin#265]
**Describe the bug**
I have my login form on the `authRedirect` page (`/login`). After my API server returns failed login (`code 401`), the plugin attempts to redirect to the same page which results into uncaught error.

**To Reproduce**
Call this.$auth.login({ ... }) on the `authRedirect` page (`/login`).

**Expected behavior**
I'd expect no redirect if login request failed and the user is already on the `authRedirect` page.

**Comment by d0whc3r** [comment]
Thanks to report, I will check asap

**Comment by janvorisek** [comment]
I also got an error on the after login route. Not sure why it attempted to redirect while logged in, but that may be related to the dev server.

I think both redirects are happening inside the `beforeEach` navigation guards, maybe some check like `if from == to then next(false)` could be implemented.
