### ISSUE TITLE
Is 1.9.0 really published?

### ISSUE THREAD

**Issue by Glandos** [d0whc3r/vue-auth-plugin#314]
I see that `1.9.0` is referenced on NPM, but neither in changelog, nor git tag, nor GitHub release.

Is this "normal"? I guess I have nothing to worry about, but I just want to be sure before updating this code :)

**Comment by d0whc3r** [comment]
Good point, thank you for the comment, I will upload a new version updating dependencies

**Comment by d0whc3r** [comment]
1.9.1 just published
