### ISSUE TITLE
[QUESTION] - User Data Object

### ISSUE THREAD

**Issue by go4cas** [d0whc3r/vue-auth-plugin#67]
My `options`:
```javascript
const options = {
  ...
  tokenStore: ['localStorage'],
  loginData: {
    url: '/auth/login',
    method: 'POST',
    redirect: '/',
    headerToken: 'Authorization',
    fetchUser: true
  },
  fetchData: {
    url: '/auth/me',
    method: 'GET',
    interval: 30,
    enabled: false
  }
}
```
Sample response from `/auth/me`:
```json
{
    "id": 1,
    "name": "My Name",
    "jobTitle": {
        "id": 1,
        "title": "Dev"
    },
    "status": {
        "id": 1,
        "title": "active",
    },
    "user": {
        "id": 19,
        "email": "me@example.com"
    }
}
```
When I call `const user = this.$auth.user()`, I get the following in the `user` object:
```json
{
        "id": 19,
        "email": "me@example.com"
 }
```
How do i get the entire payload from the API call into `user`, and not just the `user` node?

**Comment by d0whc3r** [comment]
Ok, by default it gets "user" key in fetch object, I deployed a new version (1.1.2) where by default gets all object in fetch response, and you could specify a key in fetch object using the option `fetchItem`

Feel free to reopen if something goes wrong :)

**Comment by go4cas** [comment]
Working 100%! Thanks again for the quick turn-around!
