### ISSUE TITLE
More strict?

### ISSUE THREAD

**Issue by dolgof** [d0whc3r/vue-auth-plugin#69]
Hello! Are you planning to make your ts-code more strict?
**"strictNullChecks": true,**
**"noImplicitAny": true,**

**Comment by d0whc3r** [comment]
done in https://github.com/d0whc3r/vue-auth-plugin/pull/70
I will create a new version when pipeline success

**Comment by d0whc3r** [comment]
I Just released version 1.1.3 with source more strict

**Comment by dolgof** [comment]
Excellent! All errors that occurred during the compilation are gone! Thx!
